# This workflow will build and test a .NET project located in a subfolder.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: Sample.CommerceCore
      run: dotnet restore

    - name: Build
      working-directory: Sample.CommerceCore
      run: dotnet build --no-restore

    - name: Test
      working-directory: Sample.CommerceCore
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: Sample.CommerceCore/TestResults
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
